//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.28 at 09:49:30 AM CET 
//


package be.cloud.team_statistics;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="full_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="birthday_GMT" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="team_id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="minutes_played_overall" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="nationality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="goals_overall" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="assists_overall" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="yellow_cards_overall" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="red_cards_overall" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "fullName",
    "birthdayGMT",
    "age",
    "position",
    "teamId",
    "minutesPlayedOverall",
    "nationality",
    "goalsOverall",
    "assistsOverall",
    "yellowCardsOverall",
    "redCardsOverall"
})
@XmlRootElement(name = "getPlayerStatsResponse")
public class GetPlayerStatsResponse {

    protected int id;
    @XmlElement(name = "full_name", required = true)
    protected String fullName;
    @XmlElement(name = "birthday_GMT", required = true)
    protected String birthdayGMT;
    protected int age;
    @XmlElement(required = true)
    protected String position;
    @XmlElement(name = "team_id")
    protected int teamId;
    @XmlElement(name = "minutes_played_overall")
    protected int minutesPlayedOverall;
    @XmlElement(required = true)
    protected String nationality;
    @XmlElement(name = "goals_overall")
    protected int goalsOverall;
    @XmlElement(name = "assists_overall")
    protected int assistsOverall;
    @XmlElement(name = "yellow_cards_overall")
    protected int yellowCardsOverall;
    @XmlElement(name = "red_cards_overall")
    protected int redCardsOverall;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the birthdayGMT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthdayGMT() {
        return birthdayGMT;
    }

    /**
     * Sets the value of the birthdayGMT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthdayGMT(String value) {
        this.birthdayGMT = value;
    }

    /**
     * Gets the value of the age property.
     * 
     */
    public int getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     */
    public void setAge(int value) {
        this.age = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the teamId property.
     * 
     */
    public int getTeamId() {
        return teamId;
    }

    /**
     * Sets the value of the teamId property.
     * 
     */
    public void setTeamId(int value) {
        this.teamId = value;
    }

    /**
     * Gets the value of the minutesPlayedOverall property.
     * 
     */
    public int getMinutesPlayedOverall() {
        return minutesPlayedOverall;
    }

    /**
     * Sets the value of the minutesPlayedOverall property.
     * 
     */
    public void setMinutesPlayedOverall(int value) {
        this.minutesPlayedOverall = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the goalsOverall property.
     * 
     */
    public int getGoalsOverall() {
        return goalsOverall;
    }

    /**
     * Sets the value of the goalsOverall property.
     * 
     */
    public void setGoalsOverall(int value) {
        this.goalsOverall = value;
    }

    /**
     * Gets the value of the assistsOverall property.
     * 
     */
    public int getAssistsOverall() {
        return assistsOverall;
    }

    /**
     * Sets the value of the assistsOverall property.
     * 
     */
    public void setAssistsOverall(int value) {
        this.assistsOverall = value;
    }

    /**
     * Gets the value of the yellowCardsOverall property.
     * 
     */
    public int getYellowCardsOverall() {
        return yellowCardsOverall;
    }

    /**
     * Sets the value of the yellowCardsOverall property.
     * 
     */
    public void setYellowCardsOverall(int value) {
        this.yellowCardsOverall = value;
    }

    /**
     * Gets the value of the redCardsOverall property.
     * 
     */
    public int getRedCardsOverall() {
        return redCardsOverall;
    }

    /**
     * Sets the value of the redCardsOverall property.
     * 
     */
    public void setRedCardsOverall(int value) {
        this.redCardsOverall = value;
    }

}
