//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.21 at 07:30:52 PM CET 
//


package be.cloud.team_statistics;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="common_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="matches_played" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="wins" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="wins_home" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="wins_away" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="losses" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="losses_home" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="losses_away" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="draws" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="points_per_game" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="league_position" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="goals_scored" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="goals_conceded" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "commonName",
    "matchesPlayed",
    "wins",
    "winsHome",
    "winsAway",
    "losses",
    "lossesHome",
    "lossesAway",
    "draws",
    "pointsPerGame",
    "leaguePosition",
    "goalsScored",
    "goalsConceded"
})
@XmlRootElement(name = "getTeamStatsResponse")
public class GetTeamStatsResponse {

    protected int id;
    @XmlElement(name = "common_name", required = true)
    protected String commonName;
    @XmlElement(name = "matches_played")
    protected int matchesPlayed;
    protected int wins;
    @XmlElement(name = "wins_home")
    protected int winsHome;
    @XmlElement(name = "wins_away")
    protected int winsAway;
    protected int losses;
    @XmlElement(name = "losses_home")
    protected int lossesHome;
    @XmlElement(name = "losses_away")
    protected int lossesAway;
    protected int draws;
    @XmlElement(name = "points_per_game")
    protected int pointsPerGame;
    @XmlElement(name = "league_position")
    protected int leaguePosition;
    @XmlElement(name = "goals_scored")
    protected int goalsScored;
    @XmlElement(name = "goals_conceded")
    protected int goalsConceded;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the commonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * Sets the value of the commonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonName(String value) {
        this.commonName = value;
    }

    /**
     * Gets the value of the matchesPlayed property.
     * 
     */
    public int getMatchesPlayed() {
        return matchesPlayed;
    }

    /**
     * Sets the value of the matchesPlayed property.
     * 
     */
    public void setMatchesPlayed(int value) {
        this.matchesPlayed = value;
    }

    /**
     * Gets the value of the wins property.
     * 
     */
    public int getWins() {
        return wins;
    }

    /**
     * Sets the value of the wins property.
     * 
     */
    public void setWins(int value) {
        this.wins = value;
    }

    /**
     * Gets the value of the winsHome property.
     * 
     */
    public int getWinsHome() {
        return winsHome;
    }

    /**
     * Sets the value of the winsHome property.
     * 
     */
    public void setWinsHome(int value) {
        this.winsHome = value;
    }

    /**
     * Gets the value of the winsAway property.
     * 
     */
    public int getWinsAway() {
        return winsAway;
    }

    /**
     * Sets the value of the winsAway property.
     * 
     */
    public void setWinsAway(int value) {
        this.winsAway = value;
    }

    /**
     * Gets the value of the losses property.
     * 
     */
    public int getLosses() {
        return losses;
    }

    /**
     * Sets the value of the losses property.
     * 
     */
    public void setLosses(int value) {
        this.losses = value;
    }

    /**
     * Gets the value of the lossesHome property.
     * 
     */
    public int getLossesHome() {
        return lossesHome;
    }

    /**
     * Sets the value of the lossesHome property.
     * 
     */
    public void setLossesHome(int value) {
        this.lossesHome = value;
    }

    /**
     * Gets the value of the lossesAway property.
     * 
     */
    public int getLossesAway() {
        return lossesAway;
    }

    /**
     * Sets the value of the lossesAway property.
     * 
     */
    public void setLossesAway(int value) {
        this.lossesAway = value;
    }

    /**
     * Gets the value of the draws property.
     * 
     */
    public int getDraws() {
        return draws;
    }

    /**
     * Sets the value of the draws property.
     * 
     */
    public void setDraws(int value) {
        this.draws = value;
    }

    /**
     * Gets the value of the pointsPerGame property.
     * 
     */
    public int getPointsPerGame() {
        return pointsPerGame;
    }

    /**
     * Sets the value of the pointsPerGame property.
     * 
     */
    public void setPointsPerGame(int value) {
        this.pointsPerGame = value;
    }

    /**
     * Gets the value of the leaguePosition property.
     * 
     */
    public int getLeaguePosition() {
        return leaguePosition;
    }

    /**
     * Sets the value of the leaguePosition property.
     * 
     */
    public void setLeaguePosition(int value) {
        this.leaguePosition = value;
    }

    /**
     * Gets the value of the goalsScored property.
     * 
     */
    public int getGoalsScored() {
        return goalsScored;
    }

    /**
     * Sets the value of the goalsScored property.
     * 
     */
    public void setGoalsScored(int value) {
        this.goalsScored = value;
    }

    /**
     * Gets the value of the goalsConceded property.
     * 
     */
    public int getGoalsConceded() {
        return goalsConceded;
    }

    /**
     * Sets the value of the goalsConceded property.
     * 
     */
    public void setGoalsConceded(int value) {
        this.goalsConceded = value;
    }

}
