//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.26 at 12:43:24 PM CET 
//


package be.cloud.team_statistics;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for matchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="matchType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="date_gmt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="home_team_id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="away_team_id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="referee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="attendance" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="stadium_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="home_team_goal_count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="away_team_goal_count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="home_team_corner_count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="away_team_corner_count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="home_team_yellow_cards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="home_team_red_cards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="away_team_yellow_cards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="away_team_red_cards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="home_team_shots" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="away_team_shots" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="home_team_shots_on_target" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="away_team_shots_on_target" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="home_team_shots_off_target" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="away_team_shots_off_target" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="home_team_fouls" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="away_team_fouls" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="home_team_possession" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="away_team_possession" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="team_a_xg" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="team_b_xg" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="odds_ft_draw" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="odds_ft_away_team_win" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "matchType", propOrder = {
    "id",
    "dateGmt",
    "homeTeamId",
    "awayTeamId",
    "referee",
    "attendance",
    "stadiumName",
    "homeTeamGoalCount",
    "awayTeamGoalCount",
    "homeTeamCornerCount",
    "awayTeamCornerCount",
    "homeTeamYellowCards",
    "homeTeamRedCards",
    "awayTeamYellowCards",
    "awayTeamRedCards",
    "homeTeamShots",
    "awayTeamShots",
    "homeTeamShotsOnTarget",
    "awayTeamShotsOnTarget",
    "homeTeamShotsOffTarget",
    "awayTeamShotsOffTarget",
    "homeTeamFouls",
    "awayTeamFouls",
    "homeTeamPossession",
    "awayTeamPossession",
    "teamAXg",
    "teamBXg",
    "oddsFtDraw",
    "oddsFtAwayTeamWin"
})
public class MatchType {

    protected int id;
    @XmlElement(name = "date_gmt", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateGmt;
    @XmlElement(name = "home_team_id")
    protected int homeTeamId;
    @XmlElement(name = "away_team_id")
    protected int awayTeamId;
    protected String referee;
    protected Integer attendance;
    @XmlElement(name = "stadium_name")
    protected String stadiumName;
    @XmlElement(name = "home_team_goal_count")
    protected Integer homeTeamGoalCount;
    @XmlElement(name = "away_team_goal_count")
    protected Integer awayTeamGoalCount;
    @XmlElement(name = "home_team_corner_count")
    protected Integer homeTeamCornerCount;
    @XmlElement(name = "away_team_corner_count")
    protected Integer awayTeamCornerCount;
    @XmlElement(name = "home_team_yellow_cards")
    protected Integer homeTeamYellowCards;
    @XmlElement(name = "home_team_red_cards")
    protected Integer homeTeamRedCards;
    @XmlElement(name = "away_team_yellow_cards")
    protected Integer awayTeamYellowCards;
    @XmlElement(name = "away_team_red_cards")
    protected Integer awayTeamRedCards;
    @XmlElement(name = "home_team_shots")
    protected Integer homeTeamShots;
    @XmlElement(name = "away_team_shots")
    protected Integer awayTeamShots;
    @XmlElement(name = "home_team_shots_on_target")
    protected Integer homeTeamShotsOnTarget;
    @XmlElement(name = "away_team_shots_on_target")
    protected Integer awayTeamShotsOnTarget;
    @XmlElement(name = "home_team_shots_off_target")
    protected Integer homeTeamShotsOffTarget;
    @XmlElement(name = "away_team_shots_off_target")
    protected Integer awayTeamShotsOffTarget;
    @XmlElement(name = "home_team_fouls")
    protected Integer homeTeamFouls;
    @XmlElement(name = "away_team_fouls")
    protected Integer awayTeamFouls;
    @XmlElement(name = "home_team_possession")
    protected Integer homeTeamPossession;
    @XmlElement(name = "away_team_possession")
    protected Integer awayTeamPossession;
    @XmlElement(name = "team_a_xg")
    protected BigDecimal teamAXg;
    @XmlElement(name = "team_b_xg")
    protected BigDecimal teamBXg;
    @XmlElement(name = "odds_ft_draw")
    protected BigDecimal oddsFtDraw;
    @XmlElement(name = "odds_ft_away_team_win")
    protected BigDecimal oddsFtAwayTeamWin;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the dateGmt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateGmt() {
        return dateGmt;
    }

    /**
     * Sets the value of the dateGmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateGmt(XMLGregorianCalendar value) {
        this.dateGmt = value;
    }

    /**
     * Gets the value of the homeTeamId property.
     * 
     */
    public int getHomeTeamId() {
        return homeTeamId;
    }

    /**
     * Sets the value of the homeTeamId property.
     * 
     */
    public void setHomeTeamId(int value) {
        this.homeTeamId = value;
    }

    /**
     * Gets the value of the awayTeamId property.
     * 
     */
    public int getAwayTeamId() {
        return awayTeamId;
    }

    /**
     * Sets the value of the awayTeamId property.
     * 
     */
    public void setAwayTeamId(int value) {
        this.awayTeamId = value;
    }

    /**
     * Gets the value of the referee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferee() {
        return referee;
    }

    /**
     * Sets the value of the referee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferee(String value) {
        this.referee = value;
    }

    /**
     * Gets the value of the attendance property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAttendance() {
        return attendance;
    }

    /**
     * Sets the value of the attendance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAttendance(Integer value) {
        this.attendance = value;
    }

    /**
     * Gets the value of the stadiumName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStadiumName() {
        return stadiumName;
    }

    /**
     * Sets the value of the stadiumName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStadiumName(String value) {
        this.stadiumName = value;
    }

    /**
     * Gets the value of the homeTeamGoalCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHomeTeamGoalCount() {
        return homeTeamGoalCount;
    }

    /**
     * Sets the value of the homeTeamGoalCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHomeTeamGoalCount(Integer value) {
        this.homeTeamGoalCount = value;
    }

    /**
     * Gets the value of the awayTeamGoalCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwayTeamGoalCount() {
        return awayTeamGoalCount;
    }

    /**
     * Sets the value of the awayTeamGoalCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAwayTeamGoalCount(Integer value) {
        this.awayTeamGoalCount = value;
    }

    /**
     * Gets the value of the homeTeamCornerCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHomeTeamCornerCount() {
        return homeTeamCornerCount;
    }

    /**
     * Sets the value of the homeTeamCornerCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHomeTeamCornerCount(Integer value) {
        this.homeTeamCornerCount = value;
    }

    /**
     * Gets the value of the awayTeamCornerCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwayTeamCornerCount() {
        return awayTeamCornerCount;
    }

    /**
     * Sets the value of the awayTeamCornerCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAwayTeamCornerCount(Integer value) {
        this.awayTeamCornerCount = value;
    }

    /**
     * Gets the value of the homeTeamYellowCards property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHomeTeamYellowCards() {
        return homeTeamYellowCards;
    }

    /**
     * Sets the value of the homeTeamYellowCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHomeTeamYellowCards(Integer value) {
        this.homeTeamYellowCards = value;
    }

    /**
     * Gets the value of the homeTeamRedCards property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHomeTeamRedCards() {
        return homeTeamRedCards;
    }

    /**
     * Sets the value of the homeTeamRedCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHomeTeamRedCards(Integer value) {
        this.homeTeamRedCards = value;
    }

    /**
     * Gets the value of the awayTeamYellowCards property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwayTeamYellowCards() {
        return awayTeamYellowCards;
    }

    /**
     * Sets the value of the awayTeamYellowCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAwayTeamYellowCards(Integer value) {
        this.awayTeamYellowCards = value;
    }

    /**
     * Gets the value of the awayTeamRedCards property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwayTeamRedCards() {
        return awayTeamRedCards;
    }

    /**
     * Sets the value of the awayTeamRedCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAwayTeamRedCards(Integer value) {
        this.awayTeamRedCards = value;
    }

    /**
     * Gets the value of the homeTeamShots property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHomeTeamShots() {
        return homeTeamShots;
    }

    /**
     * Sets the value of the homeTeamShots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHomeTeamShots(Integer value) {
        this.homeTeamShots = value;
    }

    /**
     * Gets the value of the awayTeamShots property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwayTeamShots() {
        return awayTeamShots;
    }

    /**
     * Sets the value of the awayTeamShots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAwayTeamShots(Integer value) {
        this.awayTeamShots = value;
    }

    /**
     * Gets the value of the homeTeamShotsOnTarget property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHomeTeamShotsOnTarget() {
        return homeTeamShotsOnTarget;
    }

    /**
     * Sets the value of the homeTeamShotsOnTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHomeTeamShotsOnTarget(Integer value) {
        this.homeTeamShotsOnTarget = value;
    }

    /**
     * Gets the value of the awayTeamShotsOnTarget property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwayTeamShotsOnTarget() {
        return awayTeamShotsOnTarget;
    }

    /**
     * Sets the value of the awayTeamShotsOnTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAwayTeamShotsOnTarget(Integer value) {
        this.awayTeamShotsOnTarget = value;
    }

    /**
     * Gets the value of the homeTeamShotsOffTarget property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHomeTeamShotsOffTarget() {
        return homeTeamShotsOffTarget;
    }

    /**
     * Sets the value of the homeTeamShotsOffTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHomeTeamShotsOffTarget(Integer value) {
        this.homeTeamShotsOffTarget = value;
    }

    /**
     * Gets the value of the awayTeamShotsOffTarget property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwayTeamShotsOffTarget() {
        return awayTeamShotsOffTarget;
    }

    /**
     * Sets the value of the awayTeamShotsOffTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAwayTeamShotsOffTarget(Integer value) {
        this.awayTeamShotsOffTarget = value;
    }

    /**
     * Gets the value of the homeTeamFouls property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHomeTeamFouls() {
        return homeTeamFouls;
    }

    /**
     * Sets the value of the homeTeamFouls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHomeTeamFouls(Integer value) {
        this.homeTeamFouls = value;
    }

    /**
     * Gets the value of the awayTeamFouls property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwayTeamFouls() {
        return awayTeamFouls;
    }

    /**
     * Sets the value of the awayTeamFouls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAwayTeamFouls(Integer value) {
        this.awayTeamFouls = value;
    }

    /**
     * Gets the value of the homeTeamPossession property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHomeTeamPossession() {
        return homeTeamPossession;
    }

    /**
     * Sets the value of the homeTeamPossession property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHomeTeamPossession(Integer value) {
        this.homeTeamPossession = value;
    }

    /**
     * Gets the value of the awayTeamPossession property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwayTeamPossession() {
        return awayTeamPossession;
    }

    /**
     * Sets the value of the awayTeamPossession property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAwayTeamPossession(Integer value) {
        this.awayTeamPossession = value;
    }

    /**
     * Gets the value of the teamAXg property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTeamAXg() {
        return teamAXg;
    }

    /**
     * Sets the value of the teamAXg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTeamAXg(BigDecimal value) {
        this.teamAXg = value;
    }

    /**
     * Gets the value of the teamBXg property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTeamBXg() {
        return teamBXg;
    }

    /**
     * Sets the value of the teamBXg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTeamBXg(BigDecimal value) {
        this.teamBXg = value;
    }

    /**
     * Gets the value of the oddsFtDraw property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOddsFtDraw() {
        return oddsFtDraw;
    }

    /**
     * Sets the value of the oddsFtDraw property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOddsFtDraw(BigDecimal value) {
        this.oddsFtDraw = value;
    }

    /**
     * Gets the value of the oddsFtAwayTeamWin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOddsFtAwayTeamWin() {
        return oddsFtAwayTeamWin;
    }

    /**
     * Sets the value of the oddsFtAwayTeamWin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOddsFtAwayTeamWin(BigDecimal value) {
        this.oddsFtAwayTeamWin = value;
    }

}
