//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.21 at 07:30:52 PM CET 
//


package be.cloud.team_statistics;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.cloud.team_statistics package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.cloud.team_statistics
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTeamStatsRequest }
     * 
     */
    public GetTeamStatsRequest createGetTeamStatsRequest() {
        return new GetTeamStatsRequest();
    }

    /**
     * Create an instance of {@link GetTeamStatsResponse }
     * 
     */
    public GetTeamStatsResponse createGetTeamStatsResponse() {
        return new GetTeamStatsResponse();
    }

}
