//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.30 at 10:57:54 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://be/cloud/team_statistics", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.cloud.team_statistics;
