//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.01.26 at 11:49:43 AM CET 
//


package be.cloud.team_statistics;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="succes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="newMinutesTotal" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "succes",
    "message",
    "newMinutesTotal"
})
@XmlRootElement(name = "updatePlayerMinutesResponse")
public class UpdatePlayerMinutesResponse {

    protected boolean succes;
    @XmlElement(required = true)
    protected String message;
    protected int newMinutesTotal;

    /**
     * Gets the value of the succes property.
     * 
     */
    public boolean isSucces() {
        return succes;
    }

    /**
     * Sets the value of the succes property.
     * 
     */
    public void setSucces(boolean value) {
        this.succes = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the newMinutesTotal property.
     * 
     */
    public int getNewMinutesTotal() {
        return newMinutesTotal;
    }

    /**
     * Sets the value of the newMinutesTotal property.
     * 
     */
    public void setNewMinutesTotal(int value) {
        this.newMinutesTotal = value;
    }

}
