// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: analytics.proto
// Protobuf Java Version: 4.33.1

package be.cloud;

@com.google.protobuf.Generated
public interface AnalysisResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.AnalysisResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();

  /**
   * <code>string recommendation = 2;</code>
   * @return The recommendation.
   */
  java.lang.String getRecommendation();
  /**
   * <code>string recommendation = 2;</code>
   * @return The bytes for recommendation.
   */
  com.google.protobuf.ByteString
      getRecommendationBytes();

  /**
   * <code>bool shouldSubstitute = 3;</code>
   * @return The shouldSubstitute.
   */
  boolean getShouldSubstitute();

  /**
   * <pre>
   * Hoe moe een speler is op een schaal van 10
   * </pre>
   *
   * <code>int32 fatigueLevel = 4;</code>
   * @return The fatigueLevel.
   */
  int getFatigueLevel();
}
