// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: analytics.proto
// Protobuf Java Version: 4.33.1

package be.cloud;

/**
 * Protobuf type {@code be.cloud.AnalysisResponse}
 */
@com.google.protobuf.Generated
public final class AnalysisResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:be.cloud.AnalysisResponse)
    AnalysisResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "AnalysisResponse");
  }
  // Use AnalysisResponse.newBuilder() to construct.
  private AnalysisResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AnalysisResponse() {
    playerName_ = "";
    recommendation_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return be.cloud.Analytics.internal_static_be_cloud_AnalysisResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return be.cloud.Analytics.internal_static_be_cloud_AnalysisResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            be.cloud.AnalysisResponse.class, be.cloud.AnalysisResponse.Builder.class);
  }

  public static final int PLAYERNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object playerName_ = "";
  /**
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  @java.lang.Override
  public java.lang.String getPlayerName() {
    java.lang.Object ref = playerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playerName_ = s;
      return s;
    }
  }
  /**
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayerNameBytes() {
    java.lang.Object ref = playerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECOMMENDATION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object recommendation_ = "";
  /**
   * <code>string recommendation = 2;</code>
   * @return The recommendation.
   */
  @java.lang.Override
  public java.lang.String getRecommendation() {
    java.lang.Object ref = recommendation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recommendation_ = s;
      return s;
    }
  }
  /**
   * <code>string recommendation = 2;</code>
   * @return The bytes for recommendation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecommendationBytes() {
    java.lang.Object ref = recommendation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recommendation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHOULDSUBSTITUTE_FIELD_NUMBER = 3;
  private boolean shouldSubstitute_ = false;
  /**
   * <code>bool shouldSubstitute = 3;</code>
   * @return The shouldSubstitute.
   */
  @java.lang.Override
  public boolean getShouldSubstitute() {
    return shouldSubstitute_;
  }

  public static final int FATIGUELEVEL_FIELD_NUMBER = 4;
  private int fatigueLevel_ = 0;
  /**
   * <pre>
   * Hoe moe een speler is op een schaal van 10
   * </pre>
   *
   * <code>int32 fatigueLevel = 4;</code>
   * @return The fatigueLevel.
   */
  @java.lang.Override
  public int getFatigueLevel() {
    return fatigueLevel_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, playerName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recommendation_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, recommendation_);
    }
    if (shouldSubstitute_ != false) {
      output.writeBool(3, shouldSubstitute_);
    }
    if (fatigueLevel_ != 0) {
      output.writeInt32(4, fatigueLevel_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, playerName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recommendation_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, recommendation_);
    }
    if (shouldSubstitute_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, shouldSubstitute_);
    }
    if (fatigueLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, fatigueLevel_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof be.cloud.AnalysisResponse)) {
      return super.equals(obj);
    }
    be.cloud.AnalysisResponse other = (be.cloud.AnalysisResponse) obj;

    if (!getPlayerName()
        .equals(other.getPlayerName())) return false;
    if (!getRecommendation()
        .equals(other.getRecommendation())) return false;
    if (getShouldSubstitute()
        != other.getShouldSubstitute()) return false;
    if (getFatigueLevel()
        != other.getFatigueLevel()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLAYERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerName().hashCode();
    hash = (37 * hash) + RECOMMENDATION_FIELD_NUMBER;
    hash = (53 * hash) + getRecommendation().hashCode();
    hash = (37 * hash) + SHOULDSUBSTITUTE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShouldSubstitute());
    hash = (37 * hash) + FATIGUELEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getFatigueLevel();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static be.cloud.AnalysisResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.AnalysisResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.AnalysisResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.AnalysisResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.AnalysisResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.AnalysisResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.AnalysisResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static be.cloud.AnalysisResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static be.cloud.AnalysisResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static be.cloud.AnalysisResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static be.cloud.AnalysisResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static be.cloud.AnalysisResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(be.cloud.AnalysisResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code be.cloud.AnalysisResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:be.cloud.AnalysisResponse)
      be.cloud.AnalysisResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return be.cloud.Analytics.internal_static_be_cloud_AnalysisResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return be.cloud.Analytics.internal_static_be_cloud_AnalysisResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              be.cloud.AnalysisResponse.class, be.cloud.AnalysisResponse.Builder.class);
    }

    // Construct using be.cloud.AnalysisResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      playerName_ = "";
      recommendation_ = "";
      shouldSubstitute_ = false;
      fatigueLevel_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return be.cloud.Analytics.internal_static_be_cloud_AnalysisResponse_descriptor;
    }

    @java.lang.Override
    public be.cloud.AnalysisResponse getDefaultInstanceForType() {
      return be.cloud.AnalysisResponse.getDefaultInstance();
    }

    @java.lang.Override
    public be.cloud.AnalysisResponse build() {
      be.cloud.AnalysisResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public be.cloud.AnalysisResponse buildPartial() {
      be.cloud.AnalysisResponse result = new be.cloud.AnalysisResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(be.cloud.AnalysisResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.playerName_ = playerName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.recommendation_ = recommendation_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.shouldSubstitute_ = shouldSubstitute_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.fatigueLevel_ = fatigueLevel_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof be.cloud.AnalysisResponse) {
        return mergeFrom((be.cloud.AnalysisResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(be.cloud.AnalysisResponse other) {
      if (other == be.cloud.AnalysisResponse.getDefaultInstance()) return this;
      if (!other.getPlayerName().isEmpty()) {
        playerName_ = other.playerName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRecommendation().isEmpty()) {
        recommendation_ = other.recommendation_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getShouldSubstitute() != false) {
        setShouldSubstitute(other.getShouldSubstitute());
      }
      if (other.getFatigueLevel() != 0) {
        setFatigueLevel(other.getFatigueLevel());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              playerName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              recommendation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              shouldSubstitute_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              fatigueLevel_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object playerName_ = "";
    /**
     * <code>string playerName = 1;</code>
     * @return The playerName.
     */
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string playerName = 1;</code>
     * @return The bytes for playerName.
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string playerName = 1;</code>
     * @param value The playerName to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      playerName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string playerName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerName() {
      playerName_ = getDefaultInstance().getPlayerName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string playerName = 1;</code>
     * @param value The bytes for playerName to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      playerName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object recommendation_ = "";
    /**
     * <code>string recommendation = 2;</code>
     * @return The recommendation.
     */
    public java.lang.String getRecommendation() {
      java.lang.Object ref = recommendation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recommendation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recommendation = 2;</code>
     * @return The bytes for recommendation.
     */
    public com.google.protobuf.ByteString
        getRecommendationBytes() {
      java.lang.Object ref = recommendation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recommendation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recommendation = 2;</code>
     * @param value The recommendation to set.
     * @return This builder for chaining.
     */
    public Builder setRecommendation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      recommendation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string recommendation = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecommendation() {
      recommendation_ = getDefaultInstance().getRecommendation();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string recommendation = 2;</code>
     * @param value The bytes for recommendation to set.
     * @return This builder for chaining.
     */
    public Builder setRecommendationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      recommendation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean shouldSubstitute_ ;
    /**
     * <code>bool shouldSubstitute = 3;</code>
     * @return The shouldSubstitute.
     */
    @java.lang.Override
    public boolean getShouldSubstitute() {
      return shouldSubstitute_;
    }
    /**
     * <code>bool shouldSubstitute = 3;</code>
     * @param value The shouldSubstitute to set.
     * @return This builder for chaining.
     */
    public Builder setShouldSubstitute(boolean value) {

      shouldSubstitute_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool shouldSubstitute = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearShouldSubstitute() {
      bitField0_ = (bitField0_ & ~0x00000004);
      shouldSubstitute_ = false;
      onChanged();
      return this;
    }

    private int fatigueLevel_ ;
    /**
     * <pre>
     * Hoe moe een speler is op een schaal van 10
     * </pre>
     *
     * <code>int32 fatigueLevel = 4;</code>
     * @return The fatigueLevel.
     */
    @java.lang.Override
    public int getFatigueLevel() {
      return fatigueLevel_;
    }
    /**
     * <pre>
     * Hoe moe een speler is op een schaal van 10
     * </pre>
     *
     * <code>int32 fatigueLevel = 4;</code>
     * @param value The fatigueLevel to set.
     * @return This builder for chaining.
     */
    public Builder setFatigueLevel(int value) {

      fatigueLevel_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hoe moe een speler is op een schaal van 10
     * </pre>
     *
     * <code>int32 fatigueLevel = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFatigueLevel() {
      bitField0_ = (bitField0_ & ~0x00000008);
      fatigueLevel_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:be.cloud.AnalysisResponse)
  }

  // @@protoc_insertion_point(class_scope:be.cloud.AnalysisResponse)
  private static final be.cloud.AnalysisResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new be.cloud.AnalysisResponse();
  }

  public static be.cloud.AnalysisResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnalysisResponse>
      PARSER = new com.google.protobuf.AbstractParser<AnalysisResponse>() {
    @java.lang.Override
    public AnalysisResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AnalysisResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnalysisResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public be.cloud.AnalysisResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

