// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: analytics.proto
// Protobuf Java Version: 4.33.1

package be.cloud;

@com.google.protobuf.Generated
public interface LivePlayerUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.LivePlayerUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();

  /**
   * <code>int32 currentHeartRate = 2;</code>
   * @return The currentHeartRate.
   */
  int getCurrentHeartRate();

  /**
   * <code>float currentLactate = 3;</code>
   * @return The currentLactate.
   */
  float getCurrentLactate();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
