// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: analytics.proto
// Protobuf Java Version: 4.33.1

package be.cloud;

@com.google.protobuf.Generated
public final class Analytics extends com.google.protobuf.GeneratedFile {
  private Analytics() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Analytics");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_LivePlayerUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_be_cloud_LivePlayerUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_AnalysisResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_be_cloud_AnalysisResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017analytics.proto\022\010be.cloud\"k\n\020LivePlaye" +
      "rUpdate\022\022\n\nplayerName\030\001 \001(\t\022\030\n\020currentHe" +
      "artRate\030\002 \001(\005\022\026\n\016currentLactate\030\003 \001(\002\022\021\n" +
      "\ttimestamp\030\004 \001(\003\"n\n\020AnalysisResponse\022\022\n\n" +
      "playerName\030\001 \001(\t\022\026\n\016recommendation\030\002 \001(\t" +
      "\022\030\n\020shouldSubstitute\030\003 \001(\010\022\024\n\014fatigueLev" +
      "el\030\004 \001(\0052g\n\020AnalyticsService\022S\n\025StreamPl" +
      "ayerAnalytics\022\032.be.cloud.LivePlayerUpdat" +
      "e\032\032.be.cloud.AnalysisResponse(\0010\001B\002P\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_be_cloud_LivePlayerUpdate_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_be_cloud_LivePlayerUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_be_cloud_LivePlayerUpdate_descriptor,
        new java.lang.String[] { "PlayerName", "CurrentHeartRate", "CurrentLactate", "Timestamp", });
    internal_static_be_cloud_AnalysisResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_be_cloud_AnalysisResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_be_cloud_AnalysisResponse_descriptor,
        new java.lang.String[] { "PlayerName", "Recommendation", "ShouldSubstitute", "FatigueLevel", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
