// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LivePlayerUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CurrentHeartRate int32                  `protobuf:"varint,1,opt,name=currentHeartRate,proto3" json:"currentHeartRate,omitempty"`
	CurrentLactate   float32                `protobuf:"fixed32,2,opt,name=currentLactate,proto3" json:"currentLactate,omitempty"`
	Timestamp        int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LivePlayerUpdate) Reset() {
	*x = LivePlayerUpdate{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivePlayerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivePlayerUpdate) ProtoMessage() {}

func (x *LivePlayerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivePlayerUpdate.ProtoReflect.Descriptor instead.
func (*LivePlayerUpdate) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *LivePlayerUpdate) GetCurrentHeartRate() int32 {
	if x != nil {
		return x.CurrentHeartRate
	}
	return 0
}

func (x *LivePlayerUpdate) GetCurrentLactate() float32 {
	if x != nil {
		return x.CurrentLactate
	}
	return 0
}

func (x *LivePlayerUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AnalysisResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Recommendation   string                 `protobuf:"bytes,1,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	ShouldSubstitute bool                   `protobuf:"varint,2,opt,name=shouldSubstitute,proto3" json:"shouldSubstitute,omitempty"`
	FatigueLevel     int32                  `protobuf:"varint,3,opt,name=fatigueLevel,proto3" json:"fatigueLevel,omitempty"` // Hoe moe een speler is op een schaal van 10
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResponse) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *AnalysisResponse) GetShouldSubstitute() bool {
	if x != nil {
		return x.ShouldSubstitute
	}
	return false
}

func (x *AnalysisResponse) GetFatigueLevel() int32 {
	if x != nil {
		return x.FatigueLevel
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\"\x84\x01\n" +
	"\x10LivePlayerUpdate\x12*\n" +
	"\x10currentHeartRate\x18\x01 \x01(\x05R\x10currentHeartRate\x12&\n" +
	"\x0ecurrentLactate\x18\x02 \x01(\x02R\x0ecurrentLactate\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x8a\x01\n" +
	"\x10AnalysisResponse\x12&\n" +
	"\x0erecommendation\x18\x01 \x01(\tR\x0erecommendation\x12*\n" +
	"\x10shouldSubstitute\x18\x02 \x01(\bR\x10shouldSubstitute\x12\"\n" +
	"\ffatigueLevel\x18\x03 \x01(\x05R\ffatigueLevel2\x8c\x01\n" +
	"\x10AnalyticsService\x12A\n" +
	"\x15StreamPlayerAnalytics\x12\x11.LivePlayerUpdate\x1a\x11.AnalysisResponse(\x010\x01\x125\n" +
	"\rAnalyzePlayer\x12\x11.LivePlayerUpdate\x1a\x11.AnalysisResponseB\rZ\v./analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_analytics_proto_goTypes = []any{
	(*LivePlayerUpdate)(nil), // 0: LivePlayerUpdate
	(*AnalysisResponse)(nil), // 1: AnalysisResponse
}
var file_analytics_proto_depIdxs = []int32{
	0, // 0: AnalyticsService.StreamPlayerAnalytics:input_type -> LivePlayerUpdate
	0, // 1: AnalyticsService.AnalyzePlayer:input_type -> LivePlayerUpdate
	1, // 2: AnalyticsService.StreamPlayerAnalytics:output_type -> AnalysisResponse
	1, // 3: AnalyticsService.AnalyzePlayer:output_type -> AnalysisResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
