syntax = "proto3";

option go_package = "./analytics";

message LivePlayerUpdate {
    int32 currentHeartRate = 1;
    float currentLactate = 2;
    int64 timestamp = 3;
}

message AnalysisResponse {
    string recommendation = 1;
    bool shouldSubstitute = 2;
    int32 fatigueLevel = 3;   // Hoe moe een speler is op een schaal van 10
    float avgHeartRate = 4;
    float avgLactate = 5;
    int32 totalMessages = 6;
    bool isFinalSummary = 7;
}

service AnalyticsService {
    // Stream zorgt voor Bidirectional Streaming --> uitbreiding
    rpc StreamPlayerAnalytics(stream LivePlayerUpdate) returns (stream AnalysisResponse); 

    rpc AnalyzePlayer(LivePlayerUpdate) returns (AnalysisResponse);
}