<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matchanalysis.proto

namespace App\Models\GPBMetadata;

class Matchanalysis
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x95\x03\x0A\x13matchanalysis.proto\x12\x08be.cloud\"k\x0A\x10LivePlayerUpdate\x12\x12\x0A\x0AplayerName\x18\x01 \x01(\x09\x12\x18\x0A\x10currentHeartRate\x18\x02 \x01(\x05\x12\x16\x0A\x0EcurrentLactate\x18\x03 \x01(\x02\x12\x11\x0A\x09timestamp\x18\x04 \x01(\x03\"n\x0A\x10AnalysisResponse\x12\x12\x0A\x0AplayerName\x18\x01 \x01(\x09\x12\x16\x0A\x0Erecommendation\x18\x02 \x01(\x09\x12\x18\x0A\x10shouldSubstitute\x18\x03 \x01(\x08\x12\x14\x0A\x0CfatigueLevel\x18\x04 \x01(\x052g\x0A\x10AnalyticsService\x12S\x0A\x15StreamPlayerAnalytics\x12\x1A.be.cloud.LivePlayerUpdate\x1A\x1A.be.cloud.AnalysisResponse(\x010\x01B&\xCA\x02\x0AApp\\Models\xE2\x02\x16App\\Models\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

