<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matchanalysis.proto

namespace App\Models;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>be.cloud.AnalysisResponse</code>
 */
class AnalysisResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string playerName = 1;</code>
     */
    protected $playerName = '';
    /**
     * Generated from protobuf field <code>string recommendation = 2;</code>
     */
    protected $recommendation = '';
    /**
     * Generated from protobuf field <code>bool shouldSubstitute = 3;</code>
     */
    protected $shouldSubstitute = false;
    /**
     * Hoe moe een speler is op een schaal van 10
     *
     * Generated from protobuf field <code>int32 fatigueLevel = 4;</code>
     */
    protected $fatigueLevel = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $playerName
     *     @type string $recommendation
     *     @type bool $shouldSubstitute
     *     @type int $fatigueLevel
     *           Hoe moe een speler is op een schaal van 10
     * }
     */
    public function __construct($data = NULL) {
        \App\Models\GPBMetadata\Matchanalysis::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string playerName = 1;</code>
     * @return string
     */
    public function getPlayerName()
    {
        return $this->playerName;
    }

    /**
     * Generated from protobuf field <code>string playerName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->playerName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string recommendation = 2;</code>
     * @return string
     */
    public function getRecommendation()
    {
        return $this->recommendation;
    }

    /**
     * Generated from protobuf field <code>string recommendation = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRecommendation($var)
    {
        GPBUtil::checkString($var, True);
        $this->recommendation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool shouldSubstitute = 3;</code>
     * @return bool
     */
    public function getShouldSubstitute()
    {
        return $this->shouldSubstitute;
    }

    /**
     * Generated from protobuf field <code>bool shouldSubstitute = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setShouldSubstitute($var)
    {
        GPBUtil::checkBool($var);
        $this->shouldSubstitute = $var;

        return $this;
    }

    /**
     * Hoe moe een speler is op een schaal van 10
     *
     * Generated from protobuf field <code>int32 fatigueLevel = 4;</code>
     * @return int
     */
    public function getFatigueLevel()
    {
        return $this->fatigueLevel;
    }

    /**
     * Hoe moe een speler is op een schaal van 10
     *
     * Generated from protobuf field <code>int32 fatigueLevel = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFatigueLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->fatigueLevel = $var;

        return $this;
    }

}

