<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matchanalysis.proto

namespace App\Models;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>be.cloud.LivePlayerUpdate</code>
 */
class LivePlayerUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string playerName = 1;</code>
     */
    protected $playerName = '';
    /**
     * Generated from protobuf field <code>int32 currentHeartRate = 2;</code>
     */
    protected $currentHeartRate = 0;
    /**
     * Generated from protobuf field <code>float currentLactate = 3;</code>
     */
    protected $currentLactate = 0.0;
    /**
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $playerName
     *     @type int $currentHeartRate
     *     @type float $currentLactate
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \App\Models\GPBMetadata\Matchanalysis::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string playerName = 1;</code>
     * @return string
     */
    public function getPlayerName()
    {
        return $this->playerName;
    }

    /**
     * Generated from protobuf field <code>string playerName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->playerName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 currentHeartRate = 2;</code>
     * @return int
     */
    public function getCurrentHeartRate()
    {
        return $this->currentHeartRate;
    }

    /**
     * Generated from protobuf field <code>int32 currentHeartRate = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentHeartRate($var)
    {
        GPBUtil::checkInt32($var);
        $this->currentHeartRate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float currentLactate = 3;</code>
     * @return float
     */
    public function getCurrentLactate()
    {
        return $this->currentLactate;
    }

    /**
     * Generated from protobuf field <code>float currentLactate = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setCurrentLactate($var)
    {
        GPBUtil::checkFloat($var);
        $this->currentLactate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

}

